hancock:
  archive_path: data/hancock/archives
  extract_path: data/hancock/extracted
  thumbnails_path: data/hancock/thumbnails
  cases_path: data/hancock/cases
  block1unifeatures: data/hancock_block1/features_uni_v2
  block1celldensities: data/hancock_block1/cell_density_measurements.csv
  block2unifeatures: data/hancock_block2/features_uni_v2
  block2celldensities: data/hancock_block2/cell_density_measurements.csv

msk:
  cases_path: data/msk_bench/cases
  metadata_path: data/msk_chord_processed

dataset:
  path: data/questions_hancock_bench.json
  msk_bench: data/questions_msk_bench.json

tools:
  drugbank: data/drugbank

openai_token: ""